transport:
  client-port: 50057
  raft-port: 50058

raft:
  node-id: 4
  raft-peers:
    1: "127.0.0.1:50052"
    2: "127.0.0.1:50054"
    3: "127.0.0.1:50056"
    5: "127.0.0.1:50060"
  client-peers:
    1: "127.0.0.1:50051"
    2: "127.0.0.1:50053"
    3: "127.0.0.1:50055"
    5: "127.0.0.1:50059"
  storage-base-dir: "internal/raft/storage/local4"