transport:
  client-port: 50059
  raft-port: 50060

raft:
  node-id: 5
  raft-peers:
    1: "127.0.0.1:50052"
    2: "127.0.0.1:50054"
    3: "127.0.0.1:50056"
    4: "127.0.0.1:50058"
    6: "127.0.0.1:50062"
    7: "127.0.0.1:50064"
  client-peers:
    1: "127.0.0.1:50051"
    2: "127.0.0.1:50053"
    3: "127.0.0.1:50055"
    4: "127.0.0.1:50057"
    6: "127.0.0.1:50061"
    7: "127.0.0.1:50063"
  store-dir: "internal/kv-store/local5"