transport:
  client-port: 50057
  raft-port: 50058

metrics:
  port: 9093


raft:
  node-id: 4
  raft-peers:
    1: "127.0.0.1:50052"
    2: "127.0.0.1:50054"
    3: "127.0.0.1:50056"
    5: "127.0.0.1:50060"
    #6: "127.0.0.1:50062"
    #7: "127.0.0.1:50064"
  storage-dir: "internal/node-storage/local4"