app:
  profile: ${APP_PROFILE}
  log-level: info
  quorum-wait-time: 30 # seconds

metrics:
  enabled: true
  address: 127.0.0.1

transport:
  network: tcp
  address: 127.0.0.1
  raft:
    max-concurrent-streams: 50
    num-stream-workers: 24
    timeout: 30s
  client:
    max-concurrent-streams: 100
    num-stream-workers: 24
    timeout: 30s

raft:
  batch-size: 35
  batch-max-wait: 20ms
  tick-interval: 100ms
  snap-count: 30_000 # Snapshot every X entries
  timeout: 10 # seconds
  step-inbox-size: 4096
  send-queue-size: 1024
  promotion-threshold: 100
  promotion-check-interval: 5s
  service-drain-timeout: 5s
  node-drain-timeout: 5s
  etcd:
    election-tick: 10
    heartbeat-tick: 1
    max-size-per-msg: 1_048_576
    max-inflight-msgs: 256
    max-uncommitted-entries-size: 1_073_741_824
  wal:
    no-sync: true