transport:
  client-port: 50051
  raft-port: 50052

raft:
  node-id: 1
  raft-peers:
    2: "127.0.0.1:50054"
    3: "127.0.0.1:50056"
    4: "127.0.0.1:50058"
    5: "127.0.0.1:50060"
  client-peers:
    2: "127.0.0.1:50053"
    3: "127.0.0.1:50055"
    4: "127.0.0.1:50057"
    5: "127.0.0.1:50059"
  storage-base-dir: "internal/raft/storage/local1"