transport:
  client-port: 50059
  raft-port: 50060

metrics:
  port: 9094

raft:
  #join: true
  node-id: 5
  raft-peers:
    1: "127.0.0.1:50052"
    2: "127.0.0.1:50054"
    3: "127.0.0.1:50056"
    4: "127.0.0.1:50058"
  storage-dir: "internal/node-storage/local5"