transport:
  client-port: 50055
  raft-port: 50056

metrics:
  port: 9092

raft:
  node-id: 3
  raft-peers:
    1: "127.0.0.1:50052"
    2: "127.0.0.1:50054"
    4: "127.0.0.1:50058"
    5: "127.0.0.1:50060"
    #6: "127.0.0.1:50062"
    #7: "127.0.0.1:50064"
  client-peers:
    1: "127.0.0.1:50051"
    2: "127.0.0.1:50053"
    4: "127.0.0.1:50057"
    5: "127.0.0.1:50059"
    #6: "127.0.0.1:50061"
    #7: "127.0.0.1:50063"
  storage-dir: "internal/kv-storage/local3"