transport:
  client-port: 50053
  raft-port: 50054

metrics:
  port: 9091

raft:
  node-id: 2
  raft-peers:
    1: "127.0.0.1:50052"
    3: "127.0.0.1:50056"
    4: "127.0.0.1:50058"
    5: "127.0.0.1:50060"
  storage-dir: "internal/node-storage/local2"