app:
  profile: ${APP_PROFILE}
  log-level: debug

transport:
  network: tcp
  address: 127.0.0.1
  timeout: 60

command:
  queue-size: 10000

raft:
  tick-interval: 100 # X seconds
  snap-count: 10_000 # Snapshot every X entries
  timeout: 5 # X seconds
  max-concurrent-streams: 5000
